<?php


use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Generated by LaraSpell
 * 
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class CreatePemesananRuanganTable extends Migration
{

    /**
     * Run the migrations.
     * 
     * @return void
     */
    public function up()
    {
        Schema::create('pemesanan_ruangan', function (Blueprint $table) {
            $table->increments("id");
            $table->string("no_pemesanan_ruangan", 255);
            $table->string("tanggal", 255);
            $table->string("nama_acara", 255);
            $table->string("waktu", 255);
            $table->string("jumlah_peserta", 255);
            $table->string("id_ruang", 255);
            $table->text("penanggung_jawab");
            $table->string("file_layout", 255);
            $table->string("keterangan", 255);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     * 
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pemesanan_ruangan');
    }

}
