<?php


use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Generated by LaraSpell
 * 
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:05 +0000
 */
class CreatePermohonanKonsumsiTable extends Migration
{

    /**
     * Run the migrations.
     * 
     * @return void
     */
    public function up()
    {
        Schema::create('permohonan_konsumsi', function (Blueprint $table) {
            $table->increments("id");
            $table->string("no_permohonan_konsumsi", 255);
            $table->string("tanggal", 255);
            $table->string("jam", 255);
            $table->string("sumber_dana", 255);
            $table->string("kegiatan", 255);
            $table->string("jenis_konsumsi", 255);
            $table->integer("jumlah");
            $table->string("pemohon", 255);
            $table->string("supervisor", 255);
            $table->string("status_supervisor", 255);
            $table->string("manajer", 255);
            $table->string("status_manajer", 255);
            $table->string("keterangan", 255);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     * 
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('permohonan_konsumsi');
    }

}
