<?php


use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Generated by LaraSpell
 * 
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:00 +0000
 */
class CreatePermohonanPemakaianKendaraanTable extends Migration
{

    /**
     * Run the migrations.
     * 
     * @return void
     */
    public function up()
    {
        Schema::create('permohonan_pemakaian_kendaraan', function (Blueprint $table) {
            $table->increments("id");
            $table->text("pemohon");
            $table->string("tujuan", 255);
            $table->string("keperluan", 255);
            $table->string("hari", 10);
            $table->string("tanggal_berangkat", 255);
            $table->string("tanggal_kembali", 255);
            $table->string("jam_berangkat", 255);
            $table->string("jam_kembali", 255);
            $table->string("penanggung_jawab", 255);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     * 
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('permohonan_pemakaian_kendaraan');
    }

}
