<?php


use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Generated by LaraSpell
 * 
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:00:32 +0000
 */
class CreateSuratPerintahJalanTable extends Migration
{

    /**
     * Run the migrations.
     * 
     * @return void
     */
    public function up()
    {
        Schema::create('surat_perintah_jalan', function (Blueprint $table) {
            $table->increments("id");
            $table->string("nopol_kendaraan", 9);
            $table->string("jenis", 20);
            $table->string("nama_pengemudi", 20);
            $table->string("tujuan", 255);
            $table->string("lama_perjalanan", 255);
            $table->string("tanggal_berangkat", 255);
            $table->string("tanggal_kembali", 255);
            $table->string("jam_berangkat", 255);
            $table->string("jam_kembali", 255);
            $table->integer("pengisian_bbm");
            $table->string("penanggung_jawab", 255);
            $table->string("penanggung_jawab_pool", 255);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     * 
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('surat_perintah_jalan');
    }

}
