<?php


use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Generated by LaraSpell
 * 
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:17 +0000
 */
class CreatePermohonanAtkTable extends Migration
{

    /**
     * Run the migrations.
     * 
     * @return void
     */
    public function up()
    {
        Schema::create('permohonan_atk', function (Blueprint $table) {
            $table->increments("id");
            $table->integer("jumlah");
            $table->string("nama_barang", 255);
            $table->integer("jumlah_diberikan");
            $table->string("keterangan", 255);
            $table->string("pemohon", 255);
            $table->string("bagian", 255);
            $table->string("penanggung_jawab", 255);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     * 
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('permohonan_atk');
    }

}
