<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class Karyawan extends Authenticatable
{
    use SoftDeletes;

    /**
     * Table name
     *
     * @var string
     */
    protected $table = "karyawan";

    /**
     * Fillable columns
     *
     * @var array
     */
    protected $fillable = [
        "nama",
        "nama_tanpa_gelar",
        "no_induk",
        "nid",
        "jabatan",
        "bidang",
        "sub_bidang",
        "grade",
        "jenis_kelamin",
        "pendidikan",
        "universitas",
        "password",
        "id_atasan",
        "id_supervisor",
        "id_manajer",
        "role"
    ];

    /**
     * The primary key for the model
     *
     * @var string
     */
    protected $primaryKey = "id";

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        "deleted_at"
    ];
}
