<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:00 +0000
 */
class PermohonanPemakaianKendaraan extends Model
{
    use SoftDeletes;

    /**
     * Table name
     *
     * @var string
     */
    protected $table = "permohonan_pemakaian_kendaraan";

    /**
     * Fillable columns
     *
     * @var array
     */
    protected $fillable = [
        "pemohon",
        'pemohon_id',
        "tujuan",
        "keperluan",
        "hari",
        "driver_id",
        "tanggal_berangkat",
        "tanggal_kembali",
        "jam_berangkat",
        "jam_kembali",
        "penanggung_jawab",
        "status_pj",
        "latlng",   
        "keterangan",
        "alasan_reject"
    ];

    /**
     * The primary key for the model
     *
     * @var string
     */
    protected $primaryKey = "id";

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        "deleted_at"
    ];
    public function spj(){

        return $this->hasOne('App\Models\SuratPerintahJalan', 'id_permohonan_pemakaian_kendaraan','id');

    }
    public function driver(){

        return $this->hasOne('App\Models\Driver', 'id','driver_id');

    }
}
