<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class Ruang extends Model
{
    use SoftDeletes;

    /**
     * Table name
     *
     * @var string
     */
    protected $table = "ruang";

    /**
     * Fillable columns
     *
     * @var array
     */
    protected $fillable = [
        "id_ruang",
        "nama_ruang",
        "kapasitas",
        "deskripsi",
        "foto_ruang"
    ];

    /**
     * The primary key for the model
     *
     * @var string
     */
    protected $primaryKey = "id";

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        "deleted_at"
    ];

    public function childRuangs()
    {
        return $this->hasMany(ChildRuang::class, 'id_parent_ruang', 'id');
    }
}
