<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class Ruang extends Model
{
    use SoftDeletes;

    /**
     * Table name
     *
     * @var string
     */
    protected $table = "ruang";

    /**
     * Fillable columns
     *
     * @var array
     */
    protected $fillable = [
        "id_ruang",
        "nama_ruang",
        "is_kombinasi",
        "kapasitas",
        "deskripsi",
        "foto_ruang"
    ];

    /**
     * The primary key for the model
     *
     * @var string
     */
    protected $primaryKey = "id";

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        "deleted_at"
    ];

    public function childRuangs()
    {
        return $this->hasMany(ChildRuang::class, 'id_parent_ruang', 'id');
    }

    /**
     * Atomic rooms that make up this room when it's a combination (is_kombinasi = true).
     */
    public function anggotaRooms()
    {
        return $this->belongsToMany(
            Ruang::class,
            'ruang_kombinasi_anggota',
            'id_ruang_kombinasi',
            'id_ruang_anggota'
        );
    }

    /**
     * Map every ruang.id (atomic or combination) to the set of atomic ruang.id
     * it physically occupies. Atomic rooms map to themselves; combination rooms
     * map to their members. Used to detect scheduling conflicts between a
     * combination room and its member rooms (and between combinations that
     * share a member).
     *
     * @return array<int, int[]>
     */
    public static function footprintMap()
    {
        $map = [];

        static::where('is_kombinasi', 0)->pluck('id')->each(function ($id) use (&$map) {
            $map[(int) $id] = [(int) $id];
        });

        DB::table('ruang_kombinasi_anggota')->get()
            ->groupBy('id_ruang_kombinasi')
            ->each(function ($rows, $comboId) use (&$map) {
                $map[(int) $comboId] = $rows->pluck('id_ruang_anggota')->map(function ($id) {
                    return (int) $id;
                })->all();
            });

        return $map;
    }
}
