<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:21 +0000
 */
class CreatePermohonanAtkRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'jumlah' => "required|max:10",
            'nama_barang' => "required|max:255",
            'jumlah_diberikan' => "required|max:10",
            'keterangan' => "required|max:255",
            'pemohon' => "required|max:255",
            'bagian' => "required|max:255",
            'penanggung_jawab' => "required|max:255"
        ];
    }
}
