<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:10 +0000
 */
class CreatePermohonanPemakaianKendaraanRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'pemohon' => "required|max:255",
            'tujuan' => "required|max:255",
            'keperluan' => "required|max:255",
            'hari' => "required|max:10",
            'tanggal_berangkat' => "required|max:255",
            'tanggal_kembali' => "required|max:255",
            'jam_berangkat' => "required|max:255",
            'jam_kembali' => "required|max:255",
            'penanggung_jawab' => "required|max:255"
        ];
    }
}
