<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class UpdatePemesananRuanganRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'no_pemesanan_ruangan' => "required|max:255",
            'tanggal' => "required|max:255",
            'nama_acara' => "required|max:255",
            'waktu' => "required|max:255",
            'jumlah_peserta' => "required|max:255",
            'id_ruang' => "required|max:255",
            'penanggung_jawab' => "required",
            'file_layout' => "required|max:255",
            'keterangan' => "required|max:255"
        ];
    }
}
