<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class UpdateKaryawanRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nama' => "required|max:120",
            'nama_tanpa_gelar' => "required|max:120",
            'no_induk' => "required|max:120",
            'nid' => "required|max:120",
            'jabatan' => "required|max:120",
            'bidang' => "required|max:120",
            'sub_bidang' => "required|max:120",
            'grade' => "required|max:120",
            'jenis_kelamin' => "required|max:120",
            'pendidikan' => "required|max:120",
            'universitas' => "required|max:120",
            'password' => "required|max:60",
            'id_atasan' => "required|max:120",
            'id_supervisor' => "required|max:120",
            'id_manajer' => "required|max:120"
        ];
    }
}
