<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:00:52 +0000
 */
class UpdateSuratPerintahJalanRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nopol_kendaraan' => "required|max:9",
            'jenis' => "required|max:20",
            'nama_pengemudi' => "required|max:20",
            'tujuan' => "required|max:255",
            'lama_perjalanan' => "required|max:255",
            'tanggal_berangkat' => "required|max:255",
            'tanggal_kembali' => "required|max:255",
            'jam_berangkat' => "required|max:255",
            'jam_kembali' => "required|max:255",
            'pengisian_bbm' => "required|max:10",
            'penanggung_jawab' => "required|max:255",
            'penanggung_jawab_pool' => "required|max:255"
        ];
    }
}
