<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:05 +0000
 */
class UpdatePermohonanKonsumsiRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'no_permohonan_konsumsi' => "required|max:255",
            'tanggal' => "required|max:255",
            'jam' => "required|max:255",
            'sumber_dana' => "required|max:255",
            'kegiatan' => "required|max:255",
            'jenis_konsumsi' => "required|max:255",
            'jumlah' => "required|max:100",
            'pemohon' => "required|max:255",
            'supervisor' => "required|max:255",
            'status_supervisor' => "required|max:255",
            'manajer' => "required|max:255",
            'status_manajer' => "required|max:255",
            'keterangan' => "required|max:255"
        ];
    }
}
