<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AnggaranSumberDana;
use App\Models\SumberDana;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class AnggaranSumberDanaController extends Controller
{

    /**
     * Anggaran sumber dana model
     *
     * @var App\Models\AnggaranSumberDana
     */
    protected $anggaranSumberDana;
    protected $sumberDana;

    /**
     * Constructor
     *
     * @param  App\Models\AnggaranSumberDana $anggaranSumberDana
     * @return void
     */
    public function __construct(AnggaranSumberDana $anggaranSumberDana, SumberDana $sumberDana)
    {
        $this->anggaranSumberDana = $anggaranSumberDana;
        $this->sumberDana = $sumberDana;
    }

    /**
     * Display list anggaran_sumber_dana
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {
        $limit = (int) $request->get('limit') ?: 10;
        $keyword = $request->get('keyword');

        $query = $this->anggaranSumberDana->query();
        $query->select([
            "id",
            "id_sumber_dana",
            "anggaran"
        ]);

        if ($keyword) {
            $query->where(function ($query) use ($keyword) {
                $query->where('id_sumber_dana', 'like', "%{$keyword}%");
            });
        }

        $data['title'] = 'List Anggaran Sumber Dana';
        $data['pagination'] = $query->paginate($limit);

        return view('admin::anggaran_sumber_dana.page-list', $data);
    }

    /**
     * Show detail anggaranSumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $anggaranSumberDana = $this->findOrFail($id);

        $data['title'] = 'Detail Anggaran Sumber Dana';
        $data['anggaranSumberDana'] = $anggaranSumberDana;

        return view('admin::anggaran_sumber_dana.page-detail', $data);
    }

    /**
     * Display form create anggaranSumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Anggaran Sumber Dana';
        // phpcs:ignore
        $data['form'] = $this->form(new AnggaranSumberDana)->withAction(route('admin::anggaran-sumber-dana.post-create'));

        return view('admin::anggaran_sumber_dana.form-create', $data);
    }

    /**
     * Insert new anggaranSumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new AnggaranSumberDana)->submit($request);

        $message = 'Anggaran Sumber Dana has been created!';
        return redirect()->route('admin::anggaran-sumber-dana.page-list')->with('info', $message);
    }

    /**
     * Display form edit anggaranSumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $anggaranSumberDana = $this->findOrFail($id);

        $data['title'] = 'Form Edit Anggaran Sumber Dana';
        // phpcs:ignore
        $data['form'] = $this->form($anggaranSumberDana)->withAction(route('admin::anggaran-sumber-dana.post-edit', [$id]));

        return view('admin::anggaran_sumber_dana.form-edit', $data);
    }

    /**
     * Update specified anggaranSumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $anggaranSumberDana = $this->findOrFail($id);

        $this->form($anggaranSumberDana)->submit($request);

        $message = 'Anggaran Sumber Dana has been updated!';
        return redirect()->route('admin::anggaran-sumber-dana.page-list')->with('info', $message);
    }

    /**
     * Delete specified anggaranSumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $anggaranSumberDana = $this->findOrFail($id);

        // Delete data
        $deleted = $anggaranSumberDana->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Anggaran Sumber Dana';
            return back()->with('danger', $message);
        }

        $message = 'Anggaran Sumber Dana has been deleted!';
        return redirect()->route('admin::anggaran-sumber-dana.page-list')->with('info', $message);
    }

    /**
     * Find anggaranSumberDana by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $anggaranSumberDana = $this->anggaranSumberDana->find($id);
        if (!$anggaranSumberDana) {
            return abort(404, 'Anggaran Sumber Dana not found');
        }

        return $anggaranSumberDana;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\AnggaranSumberDana $anggaranSumberDana
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(AnggaranSumberDana $anggaranSumberDana)
    {
        return FormModel::make($anggaranSumberDana, [
            'id_sumber_dana' => [
                'input' => "select",
                'label' => "Id Sumber Dana",
                'options' => $this->getSumberDana(),
                'rules' => [
                    "required",
                ]
            ],
            'anggaran' => [
                'input' => "number",
                'label' => "Anggaran",
                'rules' => [
                    "required",
                    "max:100"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::anggaran-sumber-dana.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

           /**
     * Get Sumber Dana
     *
     * @return array
     */
    protected function getSumberDana()
    {
        return $this->sumberDana
            ->select(['id as value', \DB::raw('concat(id, " - ", nama_sumber_dana) as label')])
            ->get()
            ->toArray();
    }
}
