<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Barang;
use App\Models\KategoriBarang;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:32 +0000
 */
class BarangController extends Controller
{

    /**
     * Barang model
     *
     * @var App\Models\Barang
     */
    protected $barang;
    protected $kategoriBarang;

    /**
     * Constructor
     *
     * @param  App\Models\Barang $barang
     * @return void
     */
    public function __construct(Barang $barang, KategoriBarang $kategoriBarang)
    {
        $this->barang = $barang;
        $this->kategoriBarang = $kategoriBarang;
    }

    /**
     * Display list barang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {
        $limit = (int) $request->get('limit') ?: 10;
        $keyword = $request->get('keyword');

        $query = $this->barang->query();
        $query->select([
            "id",
            "nama_barang",
            "id_kategori"
        ]);

        if ($keyword) {
            $query->where(function ($query) use ($keyword) {
                $query->where('nama_barang', 'like', "%{$keyword}%");
                $query->orWhere('id_kategori', 'like', "%{$keyword}%");
            });
        }

        $data['title'] = 'List Barang';
        $data['pagination'] = $query->paginate($limit);

        return view('admin::barang.page-list', $data);
    }

    /**
     * Show detail barang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $barang = $this->findOrFail($id);

        $data['title'] = 'Detail Barang';
        $data['barang'] = $barang;

        return view('admin::barang.page-detail', $data);
    }

    /**
     * Display form create barang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Barang';
        $data['form'] = $this->form(new Barang)->withAction(route('admin::barang.post-create'));

        return view('admin::barang.form-create', $data);
    }

    /**
     * Insert new barang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new Barang)->submit($request);

        $message = 'Barang has been created!';
        return redirect()->route('admin::barang.page-list')->with('info', $message);
    }

    /**
     * Display form edit barang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $barang = $this->findOrFail($id);

        $data['title'] = 'Form Edit Barang';
        $data['form'] = $this->form($barang)->withAction(route('admin::barang.post-edit', [$id]));

        return view('admin::barang.form-edit', $data);
    }

    /**
     * Update specified barang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $barang = $this->findOrFail($id);

        $this->form($barang)->submit($request);

        $message = 'Barang has been updated!';
        return redirect()->route('admin::barang.page-list')->with('info', $message);
    }

    /**
     * Delete specified barang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $barang = $this->findOrFail($id);

        // Delete data
        $deleted = $barang->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Barang';
            return back()->with('danger', $message);
        }

        $message = 'Barang has been deleted!';
        return redirect()->route('admin::barang.page-list')->with('info', $message);
    }

    /**
     * Find barang by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $barang = $this->barang->find($id);
        if (!$barang) {
            return abort(404, 'Barang not found');
        }

        return $barang;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\Barang $barang
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(Barang $barang)
    {
        return FormModel::make($barang, [
            'nama_barang' => [
                'input' => "text",
                'label' => "Nama Barang",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'id_kategori' => [
                'input' => "select",
                'label' => "Id Kategori",
                'options' => $this->getIdKategoriBarang(),
                'rules' => [
                    "required",
                    "max:255"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::barang.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

           /**
     * Get Id Barang
     *
     * @return array
     */
    protected function getIdKategoriBarang()
    {
        return $this->kategoriBarang
            ->select(['id as value', \DB::raw('concat(id, " - ", nama_kategori_barang) as label')])
            ->get()
            ->toArray();
    }
}
