<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ChildRuang;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Sat, 16 Feb 2019 07:37:54 +0000
 */
class ChildRuangController extends Controller
{

    /**
     * Child ruang model
     *
     * @var App\Models\ChildRuang
     */
    protected $childRuang;

    /**
     * Constructor
     *
     * @param  App\Models\ChildRuang $childRuang
     * @return void
     */
    public function __construct(ChildRuang $childRuang)
    {
        $this->childRuang = $childRuang;
    }

    /**
     * Display list child_ruang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {
        $limit = (int) $request->get('limit') ?: 10;
        $keyword = $request->get('keyword');

        $query = $this->childRuang->query();
        $query->select([
            "id",
            "id_parent_ruang",
            "kapasitas",
            "nama_subruang"
        ]);

        if ($keyword) {
            $query->where(function ($query) use ($keyword) {
                $query->where('id_parent_ruang', 'like', "%{$keyword}%");
                $query->orWhere('kapasitas', 'like', "%{$keyword}%");
                $query->orWhere('nama_subruang', 'like', "%{$keyword}%");
            });
        }

        $data['title'] = 'List Child Ruang';
        $data['pagination'] = $query->paginate($limit);

        return view('admin::child_ruang.page-list', $data);
    }

    /**
     * Show detail childRuang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $childRuang = $this->findOrFail($id);

        $data['title'] = 'Detail Child Ruang';
        $data['childRuang'] = $childRuang;

        return view('admin::child_ruang.page-detail', $data);
    }

    /**
     * Display form create childRuang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Child Ruang';
        $data['form'] = $this->form(new ChildRuang)->withAction(route('admin::child-ruang.post-create'));

        return view('admin::child_ruang.form-create', $data);
    }

    /**
     * Insert new childRuang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new ChildRuang)->submit($request);

        $message = 'Child Ruang has been created!';
        return redirect()->route('admin::child-ruang.page-list')->with('info', $message);
    }

    /**
     * Display form edit childRuang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $childRuang = $this->findOrFail($id);

        $data['title'] = 'Form Edit Child Ruang';
        $data['form'] = $this->form($childRuang)->withAction(route('admin::child-ruang.post-edit', [$id]));

        return view('admin::child_ruang.form-edit', $data);
    }

    /**
     * Update specified childRuang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $childRuang = $this->findOrFail($id);

        $this->form($childRuang)->submit($request);

        $message = 'Child Ruang has been updated!';
        return redirect()->route('admin::child-ruang.page-list')->with('info', $message);
    }

    /**
     * Delete specified childRuang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $childRuang = $this->findOrFail($id);

        // Delete data
        $deleted = $childRuang->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Child Ruang';
            return back()->with('danger', $message);
        }

        $message = 'Child Ruang has been deleted!';
        return redirect()->route('admin::child-ruang.page-list')->with('info', $message);
    }

    /**
     * Find childRuang by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $childRuang = $this->childRuang->find($id);
        if (!$childRuang) {
            return abort(404, 'Child Ruang not found');
        }

        return $childRuang;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\ChildRuang $childRuang
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(ChildRuang $childRuang)
    {
        return FormModel::make($childRuang, [
            'id_parent_ruang' => [
                'input' => "text",
                'label' => "Id Ruang",
                'maxlength' => "100",
                'rules' => [
                    "required",
                    "max:100"
                ]
            ],
            'kapasitas' => [
                'input' => "number",
                'label' => "Kapasitas Ruang",
                'maxlength' => "5",
                'rules' => [
                    "required",
                    "max:5"
                ]
            ],
            'nama_subruang' => [
                'input' => "text",
                'label' => "Nama Ruangan",
                'maxlength' => "100",
                'rules' => [
                    "required",
                    "max:100"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::child-ruang.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

    protected function getParentRuangan()
    {
        return $this->ruang
            ->select(['id as value', \DB::raw('concat(id, " - ", nama_subruang) as label')])
            // ->where('id_parent_ruang', '=', $this->ruang->id)
            ->get()
            ->toArray();
    }
}
