<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Driver;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class DriverController extends Controller
{

    /**
     * Karyawan model
     *
     * @var App\Models\Karyawan
     */
    protected $driver;

    /**
     * Constructor
     *
     * @param  App\Models\driver $driver
     * @return void
     */
    public function __construct(Driver $driver)
    {
        $this->driver = $driver;
    }

    /**
     * Display list karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {

        $query = $this->driver->query();

        $data['title'] = 'List driver';
        $data['pagination'] = $query->get();

        return view('admin::driver.page-list', $data);
    }

    /**
     * Show detail karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $driver = $this->findOrFail($id);

        $data['title'] = 'Detail driver';
        $data['driver'] = $driver;

        return view('admin::driver.page-detail', $data);
    }

    /**
     * Display form create karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Driver';
        $data['form'] = $this->form(new Driver)->withAction(route('admin::driver.post-create'));

        return view('admin::driver.form-create', $data);
    }

    /**
     * Insert new karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new Driver)->submit($request);

        $message = 'driver has been created!';
        return redirect()->route('admin::driver.page-list')->with('info', $message);
    }

    /**
     * Display form edit karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $driver = $this->findOrFail($id);

        $data['title'] = 'Form Edit driver';
        $data['form'] = $this->form($driver)->withAction(route('admin::driver.post-edit', [$id]));

        return view('admin::driver.form-edit', $data);
    }

    /**
     * Update specified karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $driver = $this->findOrFail($id);

        $this->form($driver)->submit($request);

        $message = 'driver has been updated!';
        return redirect()->route('admin::driver.page-list')->with('info', $message);
    }

    /**
     * Delete specified karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $driver = $this->findOrFail($id);

        // Delete data
        $deleted = $driver->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete driver';
            return back()->with('danger', $message);
        }

        $message = 'driver has been deleted!';
        return redirect()->route('admin::driver.page-list')->with('info', $message);
    }

    /**
     * Find karyawan by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $driver = $this->driver->find($id);
        if (!$driver) {
            return abort(404, 'Driver not found');
        }

        return $driver;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\Karyawan $karyawan
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(driver $driver)
    {
        return FormModel::make($driver, [
            'nama_driver' => [
                'input' => "text",
                'label' => "Nama driver",
                'maxlength' => "120",
                'rules' => [
                    "required",
                    "max:120"
                ]
            ],
            'email' => [
                'input' => "email",
                'label' => "Email",
                'maxlength' => "120",
                'rules' => [
                    "required",
                    "max:120"
                ]
            ],
            'status_driver' => [
                'input' => "select",
                'label' => "Status",
                'options' => [
                    [
                        'label' => 'Ready',
                        'value' => 'Ready'
                    ],
                    [
                        'label' => 'Not Ready',
                        'value' => 'Not Ready'
                    ]
                ],
                'rules' => [
                    "required"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::driver.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

}
