<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Karyawan;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class KaryawanController extends Controller
{

    /**
     * Karyawan model
     *
     * @var App\Models\Karyawan
     */
    protected $karyawan;

    /**
     * Constructor
     *
     * @param  App\Models\Karyawan $karyawan
     * @return void
     */
    public function __construct(Karyawan $karyawan)
    {
        $this->karyawan = $karyawan;
    }

    /**
     * Display list karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {

        $query = $this->karyawan->query();
        $query->select([
            "id",
            "nama",
            "nama_tanpa_gelar",
            "no_induk",
            "nid",
            "jabatan",
            "bidang",
            "sub_bidang",
            "grade",
            "jenis_kelamin",
            "pendidikan",
            "universitas",
            "password",
            "id_atasan",
            "id_supervisor",
            "id_manajer",
            "role"
        ]);

        $data['title'] = 'List Karyawan';
        $data['pagination'] = $query->get();

        return view('admin::karyawan.page-list', $data);
    }

    /**
     * Show detail karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $karyawan = $this->findOrFail($id);

        $data['title'] = 'Detail Karyawan';
        $data['karyawan'] = $karyawan;

        return view('admin::karyawan.page-detail', $data);
    }

    /**
     * Display form create karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Karyawan';
        $data['form'] = $this->form(new Karyawan)->withAction(route('admin::karyawan.post-create'));

        return view('admin::karyawan.form-create', $data);
    }

    /**
     * Insert new karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new Karyawan)->submit($request);

        $message = 'Karyawan has been created!';
        return redirect()->route('admin::karyawan.page-list')->with('info', $message);
    }

    /**
     * Display form edit karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $karyawan = $this->findOrFail($id);

        $data['title'] = 'Form Edit Karyawan';
        $data['form'] = $this->form($karyawan)->withAction(route('admin::karyawan.post-edit', [$id]));

        return view('admin::karyawan.form-edit', $data);
    }

    /**
     * Update specified karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $karyawan = $this->findOrFail($id);

        $this->form($karyawan)->submit($request);

        $message = 'Karyawan has been updated!';
        return redirect()->route('admin::karyawan.page-list')->with('info', $message);
    }

    /**
     * Delete specified karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $karyawan = $this->findOrFail($id);

        // Delete data
        $deleted = $karyawan->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Karyawan';
            return back()->with('danger', $message);
        }

        $message = 'Karyawan has been deleted!';
        return redirect()->route('admin::karyawan.page-list')->with('info', $message);
    }

    /**
     * Find karyawan by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $karyawan = $this->karyawan->find($id);
        if (!$karyawan) {
            return abort(404, 'Karyawan not found');
        }

        return $karyawan;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\Karyawan $karyawan
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(Karyawan $karyawan)
    {
        return FormModel::make($karyawan, [
            'nama' => [
                'input' => "text",
                'label' => "Nama",
                'maxlength' => "120",
                'rules' => [
                    "required",
                    "max:120"
                ]
            ],
            // 'nama_tanpa_gelar' => [
            //     'input' => "text",
            //     'label' => "No. Induk",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            'no_induk' => [
                'input' => "text",
                'label' => "No. Induk",
                'maxlength' => "120",
                'rules' => [
                    "required",
                    "max:120"
                ]
            ],
            // 'nid' => [
            //     'input' => "text",
            //     'label' => "NID",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            // 'jabatan' => [
            //     'input' => "text",
            //     'label' => "Jabatan",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            // 'bidang' => [
            //     'input' => "text",
            //     'label' => "Bidang",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            // 'sub_bidang' => [
            //     'input' => "text",
            //     'label' => "Sub Bidang",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            // 'grade' => [
            //     'input' => "text",
            //     'label' => "Grade",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            // 'jenis_kelamin' => [
            //     'input' => "select",
            //     'label' => "Jenis Kelamin",
            //     'options' => [
            //         [
            //             'label' => 'Laki-Laki',
            //             'value' => 'L'
            //         ],
            //         [
            //             'label' => 'Perempuan',
            //             'value' => 'P'
            //         ]
            //     ],
            //     'rules' => [
            //         "required"
            //     ]
            // ],
            // 'pendidikan' => [
            //     'input' => "text",
            //     'label' => "Pendidikan",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            // 'universitas' => [
            //     'input' => "text",
            //     'label' => "Universitas",
            //     'maxlength' => "120",
            //     'rules' => [
            //         "required",
            //         "max:120"
            //     ]
            // ],
            'password' => [
                'input' => "text",
                'label' => "Password",
                'maxlength' => "60",
                'rules' => [
                    "required",
                    "max:60"
                ]
            ],
            // 'id_atasan' => [
            //     'input' => "select",
            //     'label' => "Atasan",
            //     'options' => $this->getAtasanOptions(),
            //     'rules' => [
            //     ]
            // ],
            // 'id_supervisor' => [
            //     'input' => "select",
            //     'label' => "Supervisor",
            //     'options' => $this->getSupervisorOptions(),
            //     'rules' => [
            //     ]
            // ],
            // 'id_manajer' => [
            //     'input' => "select",
            //     'label' => "Manajer",
            //     'options' => $this->getManajerOptions(),
            //     'rules' => [
            //     ]
            // ],
            'role' => [
                'input' => "select",
                'label' => "Role",
                'options' => [
                    // [
                    //     'label' => 'Supervisor',
                    //     'value' => 'Supervisor'
                    // ],
                    // [
                    //     'label' => 'Manajer',
                    //     'value' => 'Manajer'
                    // ],
                    // [
                    //     'label' => 'Administrator',
                    //     'value' => 'Administrator'
                    // ],
                    [
                        'label' => 'Karyawan',
                        'value' => 'Karyawan'
                    ]
                ],
                'rules' => [
                    "required",
                    "max:120"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::karyawan.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

    protected function getSupervisorOptions()
    {
        return $this->karyawan
            ->select(['id as value', \DB::raw("CONCAT(no_induk,' - ',nama) AS label")])
            ->where('jabatan','like','%supervisor%')
            ->get()
            ->toArray();
    }

    protected function getManajerOptions()
    {
        return $this->karyawan
            ->select(['id as value', \DB::raw("CONCAT(no_induk,' - ',nama) AS label")])
            ->where('jabatan','like','%manajer%')
            ->get()
            ->toArray();
    }

    protected function getAtasanOptions()
    {
        return $this->karyawan
            ->select(['id as value', \DB::raw("CONCAT(no_induk,' - ',nama) AS label")])
            ->get()
            ->toArray();
    }
}
