<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\KategoriBarang;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:41 +0000
 */
class KategoriBarangController extends Controller
{

    /**
     * Kategori barang model
     *
     * @var App\Models\KategoriBarang
     */
    protected $kategoriBarang;

    /**
     * Constructor
     *
     * @param  App\Models\KategoriBarang $kategoriBarang
     * @return void
     */
    public function __construct(KategoriBarang $kategoriBarang)
    {
        $this->kategoriBarang = $kategoriBarang;
    }

    /**
     * Display list kategori_barang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {
        $limit = (int) $request->get('limit') ?: 10;
        $keyword = $request->get('keyword');

        $query = $this->kategoriBarang->query();
        $query->select([
            "id",
            "nama_kategori_barang"
        ]);

        if ($keyword) {
            $query->where(function ($query) use ($keyword) {
                $query->where('nama_kategori_barang', 'like', "%{$keyword}%");
            });
        }

        $data['title'] = 'List Kategori Barang';
        $data['pagination'] = $query->paginate($limit);

        return view('admin::kategori_barang.page-list', $data);
    }

    /**
     * Show detail kategoriBarang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $kategoriBarang = $this->findOrFail($id);

        $data['title'] = 'Detail Kategori Barang';
        $data['kategoriBarang'] = $kategoriBarang;

        return view('admin::kategori_barang.page-detail', $data);
    }

    /**
     * Display form create kategoriBarang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Kategori Barang';
        $data['form'] = $this->form(new KategoriBarang)->withAction(route('admin::kategori-barang.post-create'));

        return view('admin::kategori_barang.form-create', $data);
    }

    /**
     * Insert new kategoriBarang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new KategoriBarang)->submit($request);

        $message = 'Kategori Barang has been created!';
        return redirect()->route('admin::kategori-barang.page-list')->with('info', $message);
    }

    /**
     * Display form edit kategoriBarang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $kategoriBarang = $this->findOrFail($id);

        $data['title'] = 'Form Edit Kategori Barang';
        $data['form'] = $this->form($kategoriBarang)->withAction(route('admin::kategori-barang.post-edit', [$id]));

        return view('admin::kategori_barang.form-edit', $data);
    }

    /**
     * Update specified kategoriBarang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $kategoriBarang = $this->findOrFail($id);

        $this->form($kategoriBarang)->submit($request);

        $message = 'Kategori Barang has been updated!';
        return redirect()->route('admin::kategori-barang.page-list')->with('info', $message);
    }

    /**
     * Delete specified kategoriBarang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $kategoriBarang = $this->findOrFail($id);

        // Delete data
        $deleted = $kategoriBarang->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Kategori Barang';
            return back()->with('danger', $message);
        }

        $message = 'Kategori Barang has been deleted!';
        return redirect()->route('admin::kategori-barang.page-list')->with('info', $message);
    }

    /**
     * Find kategoriBarang by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $kategoriBarang = $this->kategoriBarang->find($id);
        if (!$kategoriBarang) {
            return abort(404, 'Kategori Barang not found');
        }

        return $kategoriBarang;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\KategoriBarang $kategoriBarang
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(KategoriBarang $kategoriBarang)
    {
        return FormModel::make($kategoriBarang, [
            'nama_kategori_barang' => [
                'input' => "text",
                'label' => "Nama Kategori Barang",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::kategori-barang.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }
}
