<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Kendaraan;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class KendaraanController extends Controller
{

    /**
     * Karyawan model
     *
     * @var App\Models\Karyawan
     */
    protected $kendaraan;

    /**
     * Constructor
     *
     * @param  App\Models\kendaraan $kendaraan
     * @return void
     */
    public function __construct(Kendaraan $kendaraan)
    {
        $this->kendaraan = $kendaraan;
    }

    /**
     * Display list karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {

        $query = $this->kendaraan->query();

        $data['title'] = 'List Kendaraan';
        $data['pagination'] = $query->get();

        return view('admin::kendaraan.page-list', $data);
    }

    /**
     * Show detail karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $kendaraan = $this->findOrFail($id);

        $data['title'] = 'Detail Kendaraan';
        $data['kendaraan'] = $kendaraan;

        return view('admin::kendaraan.page-detail', $data);
    }

    /**
     * Display form create karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Kendaraan';
        $data['form'] = $this->form(new Kendaraan)->withAction(route('admin::kendaraan.post-create'));

        return view('admin::kendaraan.form-create', $data);
    }

    /**
     * Insert new karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new Kendaraan)->submit($request);

        $message = 'Kendaraan has been created!';
        return redirect()->route('admin::kendaraan.page-list')->with('info', $message);
    }

    /**
     * Display form edit karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $kendaraan = $this->findOrFail($id);

        $data['title'] = 'Form Edit Kendaraan';
        $data['form'] = $this->form($kendaraan)->withAction(route('admin::kendaraan.post-edit', [$id]));

        return view('admin::kendaraan.form-edit', $data);
    }

    /**
     * Update specified karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $kendaraan = $this->findOrFail($id);

        $this->form($kendaraan)->submit($request);

        $message = 'Kendaraan has been updated!';
        return redirect()->route('admin::kendaraan.page-list')->with('info', $message);
    }

    /**
     * Delete specified karyawan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $kendaraan = $this->findOrFail($id);

        // Delete data
        $deleted = $kendaraan->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Kendaraan';
            return back()->with('danger', $message);
        }

        $message = 'Kendaraan has been deleted!';
        return redirect()->route('admin::kendaraan.page-list')->with('info', $message);
    }

    /**
     * Find karyawan by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $kendaraan = $this->kendaraan->find($id);
        if (!$kendaraan) {
            return abort(404, 'Kendaraan not found');
        }

        return $kendaraan;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\Karyawan $karyawan
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(Kendaraan $kendaraan)
    {
        return FormModel::make($kendaraan, [
            'nama_kendaraan' => [
                'input' => "text",
                'label' => "Nama Kendaraan",
                'maxlength' => "120",
                'rules' => [
                    "required",
                    "max:120"
                ]
            ],
            'tipe_bbm' => [
                'input' => "select",
                'label' => "Tipe BBM",

                'options' => [
                            [
                                'label' => 'Bensin',
                                'value' => 'bensin'
                            ],
                            [
                                'label' => 'Diesel',
                                'value' => 'diesel'
                            ]
                        ]
            ],
            'no_pol' => [
                'input' => "text",
                'label' => "Nomor Polisi",
                'maxlength' => "120",
                'rules' => [
                    "required",
                    "max:120"
                ]
            ],
            'status_kendaraan' => [
                'input' => "select",
                'label' => "Status",
                'options' => [
                    [
                        'label' => 'Ready',
                        'value' => 'Ready'
                    ],
                    [
                        'label' => 'Not Ready',
                        'value' => 'Not Ready'
                    ]
                ],
                'rules' => [
                    "required"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::kendaraan.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

}
