<?php

namespace App\Http\Controllers\Admin;

use App\Models\Ruang;
use App\Models\Karyawan;
use App\Models\LayoutRuang;
use App\Models\Notification;
use Illuminate\Http\Request;
use App\Models\PemesananRuangan;
use LaraSpells\FormModel\FormModel;
use App\Http\Controllers\Controller;
use Illuminate\Validation\ValidationException;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class PemesananRuanganController extends Controller
{

    /**
     * Pemesanan ruangan model
     *
     * @var App\Models\PemesananRuangan
     */
    protected $pemesananRuangan;
    protected $ruang;
    protected $karyawan;

    /**
     * Constructor
     *
     * @param  App\Models\PemesananRuangan $pemesananRuangan
     * @return void
     */
    public function __construct(PemesananRuangan $pemesananRuangan, Ruang $ruang, Karyawan $karyawan)
    {
        $this->pemesananRuangan = $pemesananRuangan;
        $this->ruang = $ruang;
        $this->karyawan = $karyawan;
    }

    /**
     * Display list pemesanan_ruangan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {

        $query = $this->pemesananRuangan->query();
        $query->select([
            "id",
            "no_pemesanan_ruangan",
            "tanggal",
            "tanggal_selesai",
            "nama_acara",
            "pemohon",
            "waktu_awal",
            "waktu_akhir",
            "jumlah_peserta",
            "id_ruang",
            "design_ruangan",
            "attachment",
            "keterangan",
            "status_supervisor",
            "status_manajer",
            "status_pj",
            "alasan_reject",
            "status_pelaksana",
            "created_at"
        ]);

        $data['title'] = 'List Pemesanan Ruangan';
        $data['pagination'] = $query->latest()->get();

        return view('admin::pemesanan_ruangan.page-list', $data);
    }

    /**
     * Check room availability for a given date/time range, same conflict
     * logic as the public booking flow (Front\FrontController::submitRuangan):
     * a booking blocks a room unless it's Rejected or already Terlaksana,
     * and combination rooms share conflicts with their member rooms via
     * Ruang::footprintMap().
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function checkAvailability(Request $request)
    {
        if (!$request->filled('tanggal') || !$request->filled('waktu_awal') || !$request->filled('waktu_akhir')) {
            return response()->json([
                'html' => '<div class="avail-empty">Tanggal, jam mulai, dan jam selesai wajib diisi.</div>',
            ]);
        }

        $conflict = $this->resolveConflict(
            $request->get('tanggal'),
            $request->get('waktu_awal'),
            $request->get('waktu_akhir')
        );

        $ruangs = $this->ruang->get();
        $ruangs->each(function ($r) use ($conflict) {
            $footprint = $conflict['footprintMap'][(int) $r->id] ?? [(int) $r->id];
            $r->is_conflicted = count(array_intersect($footprint, $conflict['conflictingAtomicIds'])) > 0;

            $names = [];
            foreach ($footprint as $atomicId) {
                foreach ($conflict['bookerNamesByAtomicId'][$atomicId] ?? [] as $name) {
                    $names[] = $name;
                }
            }
            $r->conflict_booker_names = array_values(array_unique($names));
        });

        $data['ruangs'] = $ruangs;

        return response()->json([
            'html' => view('admin::pemesanan_ruangan.partials.availability-list', $data)->render(),
        ]);
    }

    /**
     * List only the rooms that are NOT conflicted for a given date/time, for
     * populating the create/edit form's room select. When editing an
     * existing booking, pass exclude_id so the booking doesn't conflict
     * with itself.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function availableRooms(Request $request)
    {
        if (!$request->filled('tanggal') || !$request->filled('waktu_awal') || !$request->filled('waktu_akhir')) {
            return response()->json(['rooms' => []]);
        }

        $conflict = $this->resolveConflict(
            $request->get('tanggal'),
            $request->get('waktu_awal'),
            $request->get('waktu_akhir'),
            $request->get('exclude_id')
        );

        $rooms = $this->ruang->get()
            ->filter(function ($r) use ($conflict) {
                $footprint = $conflict['footprintMap'][(int) $r->id] ?? [(int) $r->id];
                return count(array_intersect($footprint, $conflict['conflictingAtomicIds'])) === 0;
            })
            ->values()
            ->map(function ($r) {
                return ['id' => $r->id, 'label' => $r->id . ' - ' . $r->nama_ruang];
            });

        return response()->json(['rooms' => $rooms]);
    }

    /**
     * Compute which atomic room ids are booked-out for a date/time range,
     * and who's occupying them. Shared by checkAvailability(), availableRooms(),
     * and assertRoomAvailable() so all three agree on exactly one definition
     * of "conflict" (same rule as the public booking flow: a booking blocks
     * unless Rejected or already Terlaksana).
     *
     * @param  string      $tanggal   Y-m-d
     * @param  string      $waktuAwalInput  H:i
     * @param  string      $waktuAkhirInput H:i
     * @param  int|null    $excludeId Booking id to ignore (the booking being edited)
     * @return array{footprintMap: array, conflictingAtomicIds: array, bookerNamesByAtomicId: array}
     */
    protected function resolveConflict($tanggal, $waktuAwalInput, $waktuAkhirInput, $excludeId = null)
    {
        $waktu_awal = intval(str_replace(':', '', $waktuAwalInput));
        $waktu_akhir = intval(str_replace(':', '', $waktuAkhirInput));

        $conflictingBookings = $this->pemesananRuangan
            ->where('tanggal_selesai', '>=', $tanggal)
            ->where('tanggal', '<=', $tanggal)
            ->where('status_pj', '!=', 'Rejected')
            ->where('status_pelaksana', 'Belum Terlaksana')
            ->when($excludeId, function ($query) use ($excludeId) {
                $query->where('id', '!=', $excludeId);
            })
            ->get()
            ->filter(function ($q) use ($waktu_awal, $waktu_akhir) {
                $time_awal = intval(date('Hi', $q->waktu_awal));
                $time_akhir = intval(date('Hi', $q->waktu_akhir));
                return $time_awal < $waktu_akhir && $waktu_awal < $time_akhir;
            });

        $footprintMap = Ruang::footprintMap();
        $conflictingAtomicIds = [];
        $bookerNamesByAtomicId = [];
        foreach ($conflictingBookings as $booking) {
            $bookingFootprint = $footprintMap[(int) $booking->id_ruang] ?? [(int) $booking->id_ruang];
            $bookerName = $booking->pemohon;
            foreach ($bookingFootprint as $atomicId) {
                $conflictingAtomicIds[] = $atomicId;
                if ($bookerName) {
                    $bookerNamesByAtomicId[$atomicId][] = $bookerName;
                }
            }
        }

        return [
            'footprintMap' => $footprintMap,
            'conflictingAtomicIds' => array_unique($conflictingAtomicIds),
            'bookerNamesByAtomicId' => $bookerNamesByAtomicId,
        ];
    }

    /**
     * Server-side guard against a room double-booking, run right before
     * save on both create and edit. Client-side filtering (availableRooms)
     * keeps the UI honest, but this is what actually prevents a conflicting
     * booking from being persisted (e.g. two admins submitting at once, or
     * a stale form). Excludes the booking's own row on edit.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    protected function assertRoomAvailable(Request $request, $excludeId = null)
    {
        $tanggal = $request->get('tanggal');
        $waktuAwal = $request->get('waktu_awal');
        $waktuAkhir = $request->get('waktu_akhir');
        $idRuang = $request->get('id_ruang');

        if (!$tanggal || !$waktuAwal || !$waktuAkhir || !$idRuang) {
            return;
        }

        $conflict = $this->resolveConflict($tanggal, $waktuAwal, $waktuAkhir, $excludeId);
        $footprint = $conflict['footprintMap'][(int) $idRuang] ?? [(int) $idRuang];
        $isConflicted = count(array_intersect($footprint, $conflict['conflictingAtomicIds'])) > 0;

        if (!$isConflicted) {
            return;
        }

        $names = [];
        foreach ($footprint as $atomicId) {
            foreach ($conflict['bookerNamesByAtomicId'][$atomicId] ?? [] as $name) {
                $names[] = $name;
            }
        }
        $names = array_values(array_unique($names));

        $message = 'Ruangan yang dipilih sudah dipakai pada tanggal dan jam tersebut'
            . (!empty($names) ? ' oleh: ' . implode(', ', $names) : '') . '.';

        throw ValidationException::withMessages(['id_ruang' => $message]);
    }

    /**
     * Show detail pemesananRuangan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $pemesananRuangan = $this->findOrFail($id);

        $notif = Notification::where('pemesanan_ruangan_id',$pemesananRuangan->id)->first();
        $notif->status = true;
        $notif->save();
        
        $data['title'] = 'Detail Pemesanan Ruangan';
        $data['pemesananRuangan'] = $pemesananRuangan;

        return view('admin::pemesanan_ruangan.page-detail', $data);
    }

    /**
     * Display form create pemesananRuangan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Pemesanan Ruangan';
        $data['form'] = $this->form(new PemesananRuangan)->withAction(route('admin::pemesanan-ruangan.post-create'));

        return view('admin::pemesanan_ruangan.form-create', $data);
    }

    /**
     * Insert new pemesananRuangan
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->assertRoomAvailable($request);

        $this->form(new PemesananRuangan)->submit($request);

        $message = 'Pemesanan Ruangan has been created!';
        return redirect()->route('admin::pemesanan-ruangan.page-list')->with('info', $message);
    }

    /**
     * Display form edit pemesananRuangan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $pemesananRuangan = $this->findOrFail($id);
        $pemesananRuangan['waktu_awal'] = date('H:i',$pemesananRuangan->waktu_awal);
        $pemesananRuangan['waktu_akhir'] = date('H:i',$pemesananRuangan->waktu_akhir);

        $data['title'] = 'Form Edit Pemesanan Ruangan';
        $data['id'] = $id;
        $data['form'] = $this->form($pemesananRuangan)->withAction(route('admin::pemesanan-ruangan.post-edit', [$id]));

        return view('admin::pemesanan_ruangan.form-edit', $data);
    }

    /**
     * Update specified pemesananRuangan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $pemesananRuangan = $this->findOrFail($id);

        $this->assertRoomAvailable($request, $id);

        $this->form($pemesananRuangan)->submit($request);

        $message = 'Pemesanan Ruangan has been updated!';
        return redirect()->route('admin::pemesanan-ruangan.page-list')->with('info', $message);
    }

    /**
     * Delete specified pemesananRuangan
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $pemesananRuangan = $this->findOrFail($id);

        // Delete data
        $deleted = $pemesananRuangan->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Pemesanan Ruangan';
            return back()->with('danger', $message);
        }

        $notif = Notification::where('pemesanan_ruangan_id',$id)->first();
        if($notif){
            $notif->delete();
        }

        $message = 'Pemesanan Ruangan has been deleted!';
        return redirect()->route('admin::pemesanan-ruangan.page-list')->with('info', $message);
    }

    /**
     * Find pemesananRuangan by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $pemesananRuangan = $this->pemesananRuangan->find($id);
        if (!$pemesananRuangan) {
            return abort(404, 'Pemesanan Ruangan not found');
        }

        return $pemesananRuangan;
    }

    public function terlaksana($id)
    {
        \DB::table('pemesanan_ruangan')
            ->where('id', '=', $id)
            ->update(['status_pelaksana' => 'Terlaksana']);

        return redirect('admin/pemesanan-ruangan')->with('info','Berhasil Merubah Status');
    }


    public function approve($id)
    {
        \DB::table('pemesanan_ruangan')
            ->where('id', '=', $id)
            ->update(['status_pj' => 'Approved']);

        $notif = Notification::where('pemesanan_ruangan_id',$id)->first();
        if($notif){
            $notif->status = true;
            $notif->save();
        }
        
        return redirect('admin/pemesanan-ruangan')->with('info','Berhasil Merubah Status');
    }

    public function reject(Request $req)
    {
        \DB::table('pemesanan_ruangan')
            ->where('id', '=', $req->id_ruangan)
            ->update(['status_pj' => 'Rejected','alasan_reject'=>$req->alasan]);

        return redirect('admin/pemesanan-ruangan')->with('info','Berhasil Merubah Status');
    }

    public function deletelist(Request $request, $id)
    {
        $pemesananRuangan = $this->findOrFail($id);

        // Delete data
        $deleted = $pemesananRuangan->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Pemesanan Ruangan';
            return back()->with('danger', $message);
        }

        $notif = Notification::where('pemesanan_ruangan_id',$id)->first();
        if($notif){
            $notif->delete();
        }
        $message = 'Pemesanan Ruangan has been deleted!';
        return redirect('/listpeminjamanruang')->with('info', $message);
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\PemesananRuangan $pemesananRuangan
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(PemesananRuangan $pemesananRuangan)
    {
        return FormModel::make($pemesananRuangan, [
            'no_pemesanan_ruangan' => [
                'input' => "text",
                'label' => "No Pemesanan Ruangan",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'pemohon' => [
                'input' => "select",
                'label' => "Pemohon",
                'options' => $this->getPemohon(),
                'rules' => [
                    "required"
                ]
            ],
            'tanggal' => [
                'input' => "datepicker",
                'label' => "Tanggal",
                'rules' => [
                    "required",
                ]
            ],
            'nama_acara' => [
                'input' => "text",
                'label' => "Nama Acara",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'waktu_awal' => [
                'input' => "timepicker",
                'label' => "Waktu Awal",
                'submit_value' => function ($value) {
                    return $value ? strtotime($value) : $value;
                },
                'rules' => [
                    "required",
                ]
            ],
            'waktu_akhir' => [
                'input' => "timepicker",
                'label' => "Waktu Akhir",
                'submit_value' => function ($value) {
                    return $value ? strtotime($value) : $value;
                },
                'rules' => [
                    "required",
                ]
            ],
            'jumlah_peserta' => [
                'input' => "number",
                'label' => "Jumlah Peserta",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'design_ruangan' => [
                'input' => "select",
                'label' => "Design Ruangan",
                'options' => $this->getLayoutRuang(),
                'rules' => [
                    "required"
                ]
            ],
            'id_ruang' => [
                'input' => "select",
                'label' => "Id Ruang",
                'options' => $this->getRuangan(),
                'rules' => [
                    "required"
                ]
            ],
            'attachment' => [
                'input' => "file",
                'label' => "Attachment",
                'delete_old_file' => false,
                'upload_disk' => "uploads",
                'upload_path' => "pemesanan_ruangan\/attachment",
                'rules' => [
                    "max:2048"
                ]
            ],
            'keterangan' => [
                'input' => "textarea",
                'label' => "Keterangan",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            // 'status_supervisor' => [
            //     'input' => "select",
            //     'label' => "Status Supervisor",
            //     'options' => [
            //         [
            //             'label' => 'Pending',
            //             'value' => 'Pending'
            //         ],
            //         [
            //             'label' => 'Rejected',
            //             'value' => 'Rejected'
            //         ],
            //         [
            //             'label' => 'Approved',
            //             'value' => 'Approved'
            //         ]
            //     ],
            //     'rules' => [
            //         "required",
            //     ]
            // ],
            // 'status_manajer' => [
            //     'input' => "select",
            //     'label' => "Status Manajer",
            //     'options' => [
            //         [
            //             'label' => 'Pending',
            //             'value' => 'Pending'
            //         ],
            //         [
            //             'label' => 'Rejected',
            //             'value' => 'Rejected'
            //         ],
            //         [
            //             'label' => 'Approved',
            //             'value' => 'Approved'
            //         ]
            //     ],
            //     'rules' => [
            //         "required",
            //     ]
            // ],
            'status_pj' => [
                'input' => "select",
                'label' => "Status Penanggung Jawab",
                'options' => [
                    [
                        'label' => 'Pending',
                        'value' => 'Pending'
                    ],
                    [
                        'label' => 'Rejected',
                        'value' => 'Rejected'
                    ],
                    [
                        'label' => 'Approved',
                        'value' => 'Approved'
                    ]
                ],
                'rules' => [
                    "required",
                ]
            ],
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::pemesanan-ruangan.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

           /**
     * Get ID Ruang
     *
     * @return array
     */
    protected function getRuangan()
    {
        return $this->ruang
            ->select(['id as value', \DB::raw('concat(id, " - ", nama_ruang) as label')])
            ->get()
            ->toArray();
    }

    protected function getPemohon()
    {
        return $this->karyawan
            ->select(['nama as value', 'nama as label'])
            ->get()
            ->toArray();
    }

    /**
     * Get Design Ruangan options (same layout list used on the public
     * booking form, App\Models\LayoutRuang: Classroom, U-Shape, etc.)
     *
     * @return array
     */
    protected function getLayoutRuang()
    {
        return LayoutRuang::select(['nama_layout_ruang as value', 'nama_layout_ruang as label'])
            ->get()
            ->toArray();
    }
}
