<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PermohonanAtk;
use App\Models\Barang;
use App\Models\Karyawan;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Thu, 19 Jul 2018 11:01:17 +0000
 */
class PermohonanAtkController extends Controller
{

    /**
     * Permohonan atk model
     *
     * @var App\Models\PermohonanAtk
     */
    protected $permohonanAtk;
    protected $barang;
    protected $karyawan;

    /**
     * Constructor
     *
     * @param  App\Models\PermohonanAtk $permohonanAtk
     * @return void
     */
    public function __construct(PermohonanAtk $permohonanAtk, Barang $barang, Karyawan $karyawan)
    {
        $this->permohonanAtk = $permohonanAtk;
        $this->barang = $barang;
        $this->karyawan = $karyawan;
    }

    /**
     * Display list permohonan_atk
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {
        $limit = (int) $request->get('limit') ?: 10;
        $keyword = $request->get('keyword');

        $query = $this->permohonanAtk->query();
        $query->select([
            "id",
            "jumlah",
            "nama_barang",
            "jumlah_diberikan",
            "keterangan",
            "pemohon",
            "status_pj",
            "bagian",
        ]);

        if ($keyword) {
            $query->where(function ($query) use ($keyword) {
                $query->where('nama_barang', 'like', "%{$keyword}%");
                $query->orWhere('keterangan', 'like', "%{$keyword}%");
                $query->orWhere('pemohon', 'like', "%{$keyword}%");
                $query->orWhere('bagian', 'like', "%{$keyword}%");
            });
        }

        $data['title'] = 'List Permohonan Atk';
        $data['pagination'] = $query->paginate($limit);

        return view('admin::permohonan_atk.page-list', $data);
    }

    /**
     * Show detail permohonanAtk
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $permohonanAtk = $this->findOrFail($id);

        $data['title'] = 'Detail Permohonan Atk';
        $data['permohonanAtk'] = $permohonanAtk;

        return view('admin::permohonan_atk.page-detail', $data);
    }

    /**
     * Display form create permohonanAtk
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Permohonan Atk';
        $data['form'] = $this->form(new PermohonanAtk)->withAction(route('admin::permohonan-atk.post-create'));

        return view('admin::permohonan_atk.form-create', $data);
    }

    /**
     * Insert new permohonanAtk
     *
     * @param  App\Http\Requests\Admin\CreatePermohonanAtkRequest $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(CreatePermohonanAtkRequest $request)
    {
        $this->form(new PermohonanAtk)->submit($request);

        $message = 'Permohonan ATK has been created!';
        return redirect()->route('admin::permohonan-ATK.page-list')->with('info', $message);
    }

    /**
     * Display form edit permohonanAtk
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
         $permohonanAtk = $this->findOrFail($id);

        $data['title'] = 'Form Edit Permohonan Konsumsi';
        $data['form'] = $this->form($permohonanAtk)->withAction(route('admin::permohonan-atk.post-edit', [$id]));

        return view('admin::permohonan_atk.form-edit', $data);
    }

    /**
     * Update specified permohonanAtk
     *
     * @param  App\Http\Requests\Admin\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $permohonanAtk = $this->findOrFail($id);
        $permohonanAtk->jumlah = $request->jumlah;
        $permohonanAtk->nama_barang = $request->nama_barang;
        $permohonanAtk->jumlah_diberikan = $request->jumlah_diberikan;
        $permohonanAtk->keterangan = $request->keterangan;
        $permohonanAtk->pemohon = $request->pemohon;
        $permohonanAtk->bagian = $request->bagian;
        $permohonanAtk->status_pj = $request->status_pj;
        $permohonanAtk->save();

        $message = 'Permohonan ATK has been updated!';
        return redirect()->route('admin::permohonan-atk.page-list')->with('info', $message);
    }

    /**
     * Delete specified permohonanAtk
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $permohonanAtk = $this->findOrFail($id);

        // Delete data
        $deleted = $permohonanAtk->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Permohonan Atk';
            return back()->with('danger', $message);
        }

        $message = 'Permohonan Atk has been deleted!';
        return redirect()->route('admin::permohonan-atk.page-list')->with('info', $message);
    }

    /**
     * Find permohonanAtk by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $permohonanAtk = $this->permohonanAtk->find($id);
        if (!$permohonanAtk) {
            return abort(404, 'Permohonan Atk not found');
        }

        return $permohonanAtk;
    }

   /**
     * Setup FormModel
     *
     * @param  App\Models\PermohonanPemakaianKendaraan $permohonanPemakaianKendaraan
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(PermohonanAtk $permohonanAtk)
    {
        return FormModel::make($permohonanAtk, [
            'nama_barang' => [
                'input' => "select",
                'label' => "Nama Barang",
                'options' => $this->getBarang(),
                'rules' => [
                    "required"
                ]
            ],
            'jumlah' => [
                'input' => "number",
                'label' => "Jumlah",
                'rules' => [
                    "required",
                    "max:1000"
                ]
            ],
            'jumlah_diberikan' => [
                'input' => "number",
                'label' => "Jumlah Diberikan",
                'rules' => [
                    "required",
                    "max:1000"
                ]
            ],
            'keterangan' => [
                'input' => "textarea",
                'label' => "Keterangan",
                'rules' => [
                    "required"
                ]
            ],
            'pemohon' => [
                'input' => "text",
                'label' => "Pemohon",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'bagian' => [
                'input' => "text",
                'label' => "Bagian",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'status_pj' => [
                'input' => "select",
                'label' => "Status PJ",
                'options' => [
                    [
                        'label' => 'Pending',
                        'value' => 'Pending'
                    ],
                    [
                        'label' => 'Rejected',
                        'value' => 'Rejected'
                    ],
                    [
                        'label' => 'Approved',
                        'value' => 'Approved'
                    ]
                ],
                'rules' => [
                    "required",
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::permohonan-pemakaian-kendaraan.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }

           /**
     * Get Barang
     *
     * @return array
     */
    protected function getBarang()
    {
        return $this->barang
            ->select(['id as value', \DB::raw('concat(id, " - ", nama_barang) as label')])
            ->get()
            ->toArray();
    }

         /**
     * Get Penanggung Jawab
     *
     * @return array
     */
    protected function getPenanggungJawab()
    {
        return $this->karyawan
            ->select(['id as value', 'nama as label'])
            ->where('role', 'manajer')
            ->get()
            ->toArray();
    }
}
