<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Ruang;
use App\Models\ChildRuang;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class RuangController extends Controller
{

    /**
     * Ruang model
     *
     * @var App\Models\Ruang
     */
    protected $ruang;
    protected $childRuang;

    /**
     * Constructor
     *
     * @param  App\Models\Ruang $ruang
     * @return void
     */
    public function __construct(Ruang $ruang, ChildRuang $childRuang)
    {
        $this->ruang = $ruang;
        $this->childRuang = $childRuang;
    }

    /**
     * Display list ruang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {

        $query = $this->ruang->query();
        $query->select([
            "id",
            "id_ruang",
            "nama_ruang",
            "kapasitas",
            "deskripsi",
            "foto_ruang"
        ]);

        $data['title'] = 'List Ruang';
        $data['pagination'] = $query->get();

        return view('admin::ruang.page-list', $data);
    }

    /**
     * Show detail ruang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $ruang = $this->findOrFail($id);

        $data['title'] = 'Detail Ruang';
        $data['ruang'] = $ruang;

        return view('admin::ruang.page-detail', $data);
    }

    /**
     * Display form create ruang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Ruang';
        $data['form'] = $this->form(new Ruang)->withAction(route('admin::ruang.post-create'));

        return view('admin::ruang.form-create', $data);
    }

    /**
     * Insert new ruang
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new Ruang)->submit($request);

        $message = 'Ruang has been created!';
        return redirect()->route('admin::ruang.page-list')->with('info', $message);
    }

    /**
     * Display form edit ruang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $ruang = $this->findOrFail($id);

        $data['title'] = 'Form Edit Ruang';
        $data['form'] = $this->form($ruang)->withAction(route('admin::ruang.post-edit', [$id]));

        return view('admin::ruang.form-edit', $data);
    }

    /**
     * Update specified ruang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $ruang = $this->findOrFail($id);

        $this->form($ruang)->submit($request);

        $message = 'Ruang has been updated!';
        return redirect()->route('admin::ruang.page-list')->with('info', $message);
    }

    /**
     * Delete specified ruang
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $ruang = $this->findOrFail($id);

        // Delete data
        $deleted = $ruang->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Ruang';
            return back()->with('danger', $message);
        }

        $message = 'Ruang has been deleted!';
        return redirect()->route('admin::ruang.page-list')->with('info', $message);
    }

    /**
     * Find ruang by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $ruang = $this->ruang->find($id);
        if (!$ruang) {
            return abort(404, 'Ruang not found');
        }

        return $ruang;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\Ruang $ruang
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(Ruang $ruang)
    {
        return FormModel::make($ruang, [
            'id_ruang' => [
                'input' => "text",
                'label' => "Id Ruang",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'nama_ruang' => [
                'input' => "text",
                'label' => "Nama Ruang",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'kapasitas' => [
                'input' => "number",
                'label' => "Kapasitas",
                'maxlength' => "10",
                'rules' => [
                    "required",
                    "max:10"
                ]
            ],
            'deskripsi' => [
                'input' => "textarea",
                'label' => "Deskripsi",
                'rules' => [
                    "required",
                    "max:120"
                ]
            ],
            'foto_ruang' => [
                'input' => "file",
                'label' => "Foto Ruangan",
                'delete_old_file' => true,
                'upload_disk' => "uploads",
                'upload_path' => "ruangan\/foto_ruang",
                'rules' => [
                    "required",
                    "max:10000"
                ]
            ]
            // 'childRuangs' => [
            //     'label' => 'Sub-Ruang',
            //     'fields' => [
            //         'nama_subruang' => [
            //             'input' => "text",
            //             'label' => "Nama Ruang",
            //             'maxlength' => "255",
            //             'rules' => [
            //                 "required",
            //                 "max:255"
            //             ]
            //         ],
            //         'kapasitas' => [
            //             'input' => "number",
            //             'label' => "Kapasitas",
            //             'maxlength' => "10",
            //             'rules' => [
            //                 "required",
            //                 "max:10"
            //             ]
            //         ],
            //     ]
            // ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::ruang.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }
}
