<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\SumberDana;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Wed, 06 Jun 2018 09:10:06 +0000
 */
class SumberDanaController extends Controller
{

    /**
     * Sumber dana model
     *
     * @var App\Models\SumberDana
     */
    protected $sumberDana;

    /**
     * Constructor
     *
     * @param  App\Models\SumberDana $sumberDana
     * @return void
     */
    public function __construct(SumberDana $sumberDana)
    {
        $this->sumberDana = $sumberDana;
    }

    /**
     * Display list sumber_dana
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {
        $limit = (int) $request->get('limit') ?: 10;
        $keyword = $request->get('keyword');

        $query = $this->sumberDana->query();
        $query->select([
            "id",
            "nama_sumber_dana"
        ]);

        if ($keyword) {
            $query->where(function ($query) use ($keyword) {
                $query->where('nama_sumber_dana', 'like', "%{$keyword}%");
            });
        }

        $data['title'] = 'List Sumber Dana';
        $data['pagination'] = $query->paginate($limit);

        return view('admin::sumber_dana.page-list', $data);
    }

    /**
     * Show detail sumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $sumberDana = $this->findOrFail($id);

        $data['title'] = 'Detail Sumber Dana';
        $data['sumberDana'] = $sumberDana;

        return view('admin::sumber_dana.page-detail', $data);
    }

    /**
     * Display form create sumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Sumber Dana';
        $data['form'] = $this->form(new SumberDana)->withAction(route('admin::sumber-dana.post-create'));

        return view('admin::sumber_dana.form-create', $data);
    }

    /**
     * Insert new sumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new SumberDana)->submit($request);

        $message = 'Sumber Dana has been created!';
        return redirect()->route('admin::sumber-dana.page-list')->with('info', $message);
    }

    /**
     * Display form edit sumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $sumberDana = $this->findOrFail($id);

        $data['title'] = 'Form Edit Sumber Dana';
        $data['form'] = $this->form($sumberDana)->withAction(route('admin::sumber-dana.post-edit', [$id]));

        return view('admin::sumber_dana.form-edit', $data);
    }

    /**
     * Update specified sumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $sumberDana = $this->findOrFail($id);

        $this->form($sumberDana)->submit($request);

        $message = 'Sumber Dana has been updated!';
        return redirect()->route('admin::sumber-dana.page-list')->with('info', $message);
    }

    /**
     * Delete specified sumberDana
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $sumberDana = $this->findOrFail($id);

        // Delete data
        $deleted = $sumberDana->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Sumber Dana';
            return back()->with('danger', $message);
        }

        $message = 'Sumber Dana has been deleted!';
        return redirect()->route('admin::sumber-dana.page-list')->with('info', $message);
    }

    /**
     * Find sumberDana by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $sumberDana = $this->sumberDana->find($id);
        if (!$sumberDana) {
            return abort(404, 'Sumber Dana not found');
        }

        return $sumberDana;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\SumberDana $sumberDana
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(SumberDana $sumberDana)
    {
        return FormModel::make($sumberDana, [
            'nama_sumber_dana' => [
                'input' => "text",
                'label' => "Nama Sumber Dana",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::sumber-dana.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }
}
