<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Test;
use Illuminate\Http\Request;
use LaraSpells\FormModel\FormModel;

/**
 * Generated by LaraSpell
 *
 * @author  Ditama Digital <info@ditamadigtal.co.id>
 * @created Mon, 05 Feb 2018 17:24:59 +0000
 */
class TestController extends Controller
{

    /**
     * Test model
     *
     * @var App\Models\Test
     */
    protected $test;

    /**
     * Constructor
     *
     * @param  App\Models\Test $test
     * @return void
     */
    public function __construct(Test $test)
    {
        $this->test = $test;
    }

    /**
     * Display list test
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function pageList(Request $request)
    {
        $limit = (int) $request->get('limit') ?: 10;
        $keyword = $request->get('keyword');

        $query = $this->test->query();
        $query->select([
            "id",
            "nama",
            "field1"
        ]);

        if ($keyword) {
            $query->where(function ($query) use ($keyword) {
                $query->where('nama', 'like', "%{$keyword}%");
                $query->orWhere('field1', 'like', "%{$keyword}%");
            });
        }

        $data['title'] = 'List Test';
        $data['pagination'] = $query->paginate($limit);

        return view('admin::test.page-list', $data);
    }

    /**
     * Show detail test
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function pageDetail(Request $request, $id)
    {
        $test = $this->findOrFail($id);

        $data['title'] = 'Detail Test';
        $data['test'] = $test;

        return view('admin::test.page-detail', $data);
    }

    /**
     * Display form create test
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function formCreate(Request $request)
    {
        $data['title'] = 'Form Create Test';
        $data['form'] = $this->form(new Test)->withAction(route('admin::test.post-create'));

        return view('admin::test.form-create', $data);
    }

    /**
     * Insert new test
     *
     * @param  Illuminate\Http\Request $request
     * @return Illuminate\Http\Response
     */
    public function postCreate(Request $request)
    {
        $this->form(new Test)->submit($request);

        $message = 'Test has been created!';
        return redirect()->route('admin::test.page-list')->with('info', $message);
    }

    /**
     * Display form edit test
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function formEdit(Request $request, $id)
    {
        $test = $this->findOrFail($id);

        $data['title'] = 'Form Edit Test';
        $data['form'] = $this->form($test)->withAction(route('admin::test.post-edit', [$id]));

        return view('admin::test.form-edit', $data);
    }

    /**
     * Update specified test
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function postEdit(Request $request, $id)
    {
        $test = $this->findOrFail($id);

        $this->form($test)->submit($request);

        $message = 'Test has been updated!';
        return redirect()->route('admin::test.page-list')->with('info', $message);
    }

    /**
     * Delete specified test
     *
     * @param  Illuminate\Http\Request $request
     * @param  string $id
     * @return Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $test = $this->findOrFail($id);

        // Delete data
        $deleted = $test->delete();
        if (!$deleted) {
            $message = 'Something went wrong when delete Test';
            return back()->with('danger', $message);
        }

        $message = 'Test has been deleted!';
        return redirect()->route('admin::test.page-list')->with('info', $message);
    }

    /**
     * Find test by 'id' or display 404 if not exists
     *
     * @return Illuminate\Http\Response
     */
    protected function findOrFail($id)
    {
        $test = $this->test->find($id);
        if (!$test) {
            return abort(404, 'Test not found');
        }

        return $test;
    }

    /**
     * Setup FormModel
     *
     * @param  App\Models\Test $test
     * @return LaraSpells\FormModel\FormModel
     */
    protected function form(Test $test)
    {
        return FormModel::make($test, [
            'nama' => [
                'input' => "text",
                'label' => "Nama",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ],
            'field1' => [
                'input' => "text",
                'label' => "Field 1",
                'maxlength' => "255",
                'rules' => [
                    "required",
                    "max:255"
                ]
            ]
        ])->withViewData([
            // phpcs:ignore
            'before_button_save' => '<a class="btn btn-default" href="'.route('admin::test.page-list').'"><i class="fa fa-chevron-left"></i> Cancel</a>&nbsp;',
        ]);
    }
}
